### ISSUE TITLE
Hasmanythrough is using the wrong id

### ISSUE THREAD

**Issue by ghost** [yajra/laravel-datatables#1526]
### Summary of problem or feature request

So I have a hasmanythrough relationship, in my user's model like so:

    /**
     * Get the meetings
     *
     * @return App\Models\Meetings\Meetings
     */
    public function meetings()
    {
        return $this->hasManyThrough('App\Models\Meetings\Meetings', 'App\Models\Jobs\Apply');
    }

when I `dd` the following `Auth::user()->meetings()->get()` inside a controller it returns the correct information . Now inside my datatable class, when I use that for my records it returns the id for the 'apply' table rather than the 'meetings' table, 

**My datatable query:**

    /**
     * Get the query object to be processed by dataTables.
     *
     * @return \Illuminate\Database\Eloquent\Builder|\Illuminate\Database\Query\Builder|\Illuminate\Support\Collection
     */
    public function query()
    {
        $query = Auth::user()->meetings($this->getColumns());

        return $this->applyScopes($query);
    }

When I `dd` the variable inside my `dataTable` method, it shows the id from the other table, for example:

**Controller:**

<img src="https://i.imgur.com/fLEJqkg.png">

**Inside datatables** 

<img src="https://i.imgur.com/m197g5y.png">

As you can see, the id should be 3, rather than 16, which is the 'apply_id'

### Code snippet of problem

Structure:

        Schema::create('advertisement_meetings', function (Blueprint $table) {
            $table->increments('id');
            $table->string('name');
            $table->string('room');
            $table->date('date');
            $table->time('start');
            $table->time('end');
            $table->string('status');
            $table->text('notes');
            $table->integer('apply_id');
            $table->string('address');
            $table->string('street');
            $table->string('city');
            $table->string('country');
            $table->string('postal');
            $table->string('lat');
            $table->string('long');
            $table->timestamps();
            $table->softDeletes();  
        });

        Schema::create('advertisement_applications', function (Blueprint $table) {
            $table->increments('id');
            $table->timestamps();
            $table->unsignedInteger('user_id');
            $table->unsignedInteger('job_id');
            $table->unsignedInteger('resume_id');
            $table->string('status')->default('pending');
        });

**User relationship:**

    /**
     * Get the meetings
     *
     * @return App\Models\Meetings\Meetings
     */
    public function meetings()
    {
        return $this->hasManyThrough('App\Models\Meetings\Meetings', 'App\Models\Jobs\Apply');
    }

**My datatable class**

    <?php

    namespace App\Tables\Meetings;

    use App\Models\Jobs\Apply;
    use Illuminate\Support\Facades\Auth;
    use Yajra\DataTables\EloquentDataTable;
    use Yajra\DataTables\Services\DataTable;
    use App\Models\Meetings\Meetings;

    class MeetingsDatatable extends DataTable
    {
        /**
        * Build DataTable class.
        *
        * @return \Yajra\Datatables\Engines\BaseEngine
        */
        public function dataTable($query)
        {
            $dataTable = new EloquentDataTable($query);

            return $dataTable
                ->addColumn('DT_RowId', function($meetings){
                    return 'meetings-' . $meetings->mid;
                })
                ->addColumn('action', function($meetings) { 
                    dd($meetings);
                    $buttons = [
                        'objectid'    => $meetings->id,
                        'identifier'  => 'meetings',
                        'show_path'   => 'meetings.show',
                        'edit'   => 'meetings.edit',
                    ];

                    return view('partials.table-buttons', compact('buttons'))->render();
                })
                ->rawColumns(['action']);
        }

        /**
        * Get the query object to be processed by dataTables.
        *
        * @return \Illuminate\Database\Eloquent\Builder|\Illuminate\Database\Query\Builder|\Illuminate\Support\Collection
        */
        public function query()
        {
            $query = Auth::user()->meetings($this->getColumns());

            return $this->applyScopes($query);
        }

        /**
        * Optional method if you want to use html builder.
        *
        * @return \Yajra\Datatables\Html\Builder
        */
        public function html()
        {
            return $this->builder()
                ->columns(['name', 'room', 'start', 'end', 'date', 'notes'])
                ->minifiedAjax('')
                ->addAction(['width' => '80px'])
                ->parameters([
                    'dom'     => '<"datatable-header"fl><"datatable-scroll"t><"datatable-footer"ip>B',
                    'order'   => [[0, 'desc']],
                    'buttons' => [
                        'export',
                        'print',
                        'reset',
                        'reload',
                    ],
                ]);
        }

        /**
        * Get columns.
        *
        * @return array
        */
        protected function getColumns()
        {
            return [
                'advertisement_meetings.id',
                'name', 
                'date',
                'start',
                'end',
                'created_at',
            ];
        }

        /**
        * Get filename for export.
        *
        * @return string
        */
        protected function filename()
        {
            return 'meetings_' . time();
        }
    }

**Comment by yajra** [comment]
Maybe try selecting all fields from meeting?

```php
$query = Auth::user()->meetings('advertisement_meetings.*');
```

**Comment by filtration** [comment]
That seems to still be getting the same Id as before

<img src="https://i.imgur.com/4cHRd53.png">

Everything else seems fine, just not the id...

My meetings model:


    <?php

    namespace App\Models\Meetings;

    use Illuminate\Database\Eloquent\Model;

    class Meetings extends Model
    {
        /**
        * The table associated with the model.
        *
        * @var string
        */
        protected $table = 'advertisement_meetings';
        
        /**
        * The attributes that should be mutated to dates.
        *
        * @var array
        */
        protected $dates = [
            'created_at',
            'updated_at',
            'deleted_at',
            'date',
        ];

        /**
        * The attributes that are mass assignable.
        *
        * @var array
        */
        protected $fillable = [
            'name',
            'room',
            'date',
            'start',
            'end',
            'status',
            'notes',
            'address',
            'street',
            'city',
            'postal',
            'country',
            'lat',
            'long',
            'apply_id'
        ];

        /**
        * Get the user
        *
        * @return 
        */
        public function user()
        {
            return $this->belongsTo('App\Models\Account\User');
        }
    }


and my apply model

    <?php

    namespace App\Models\Jobs;

    use Illuminate\Database\Eloquent\Model;
    use Illuminate\Support\Facades\Auth;

    class Apply extends Model
    {
        /**
         * The table associated with the model.
         *
         * @var string
         */
        protected $table = 'advertisement_applications';

        /**
         * The attributes that are mass assignable.
         *
         * @var array
         */
        protected $fillable = [
            'status',
            'resume_id',
        ];

        /**
         * The attributes that should be mutated to dates.
         *
         * @var array
         */
        protected $dates = [
            'created_at',
            'updated_at',
            'deleted_at'
        ];

        /**
         * The event map for the model.
         *
         * @var array
         */
        protected $dispatchesEvents = [
            //'created' => 'App\Events\Applications\ApplicationUpdatedEvent',
            'updated' => 'App\Events\Applications\ApplicationUpdatedEvent',
        ];

        /**
         * The attributes that should be cast to native types.
         *
         * @var array
         */
        protected $casts = [
            'status' => 'string',
        ];

        /**
         * Get the job
         *
         * @return App\Models\Jobs\Jobs
         */
        public function job()
        {
            return $this->belongsTo('App\Models\Jobs\Jobs');
        }

        /**
         * Get the user
         *
         * @return App\Models\Account\User
         */
        public function user()
        {
            return $this->belongsTo('App\Models\Account\User', 'user_id');
        }

        /**
         * Get the resume
         *
         * @return App\Models\Resumes\Resume
         */
        public function resume()
        {
            return $this->belongsTo('App\Models\Resumes\Resume', 'resume_id');
        }

        /**
         * Check if the user has applied
         *
         * @param [type] $id
         * @param [type] $user
         * @return void
         */
        public function HasApplied($id, $user)
        {
            $apply = new Apply();
            
            // $applied = $apply
            //     ->find($id)
            //     ->dump
            // 	->User($user)
            // 	->get();

            // if(!$applied->isEmpty()){
            //     return true;
            // }
            return false;
        }

        public function ScopeUser($query, $id = null)
        {
            if($id){
                return $query->where('user_id', $id);    
            }
            return $query->where('user_id', Auth::user()->id);
        }

        public function ScopeJob($query, $id)
        {
            return $query->where('job_id', $id);
        }	

        /**
         * Get the applications in the past month
         *
         * @param [type] $query
         * @return void
         */
        public function ScopePastMonth($query)
        {
            // current date
            $date = new \Carbon\Carbon;

            // get the results for the past month
            $date->subMonth();

            return $query
                ->where('created_at', '>', $date->toDateTimeString());
        }
        
        public function ScopeJoinJobs($query)
        {
            return $query->join('jobs', 'job_id', '=', 'jobs.id');
        }

        public function scopeSearchKeyword($query, $keyword)
        {
            return $query->where("jobs.name", "like", "%$keyword%");
        }

        public function scopeSearchLocation($query, $location)
        {
            return $query->where("jobs.address_country", "like", "%$location%");
        }

        public function scopeSearchDateApplied($query, $date)
        {
            //new formatted date
            $parsedDate = \Carbon\Carbon::parse($date)->format('Y-m-d');

            if($date){
                return $query->whereDate("jobs_applications.created_at", $parsedDate);
            }
        }
    }

**Comment by filtration** [comment]
So, I was checked the elquoent class, and when the getQuery() is run, it's pulling the latter table thus overwriting the main table.

I fixed my problem by using ->select($this->getColumns()) on my query with the table name that I want, for example:

    /**
    * Get the query object to be processed by dataTables.
    *
    * @return \Illuminate\Database\Eloquent\Builder|\Illuminate\Database\Query\Builder|\Illuminate\Support\Collection
    */
    public function query()
    {
        $query = Auth::user()->meetings()->select($this->getColumns());

        return $this->applyScopes($query);
    }

    protected function getColumns()
    {
        return [
            'meetings.advertisement_meetings.id',
            'meetings.name', 
            'meetings.date',
            'meetings.start',
            'meetings.end',
            'meetings.created_at',
        ];
    }

You will need the table name otherwise it will be ambigious. I don't know why getQuery() is pulling the wrong information in the EloquentDataTable class `construct` this may be an issue with Laravel or this package... but thats' what's causing it anyway.

**Comment by yajra** [comment]
@filtration thanks for this findings. Would you mind sending a PR for a possible fix? I'm a bit occupied and might to take a look at this earlier next year.

**Comment by yajra** [comment]
BTW, for the wrong ID, it is written in this [demo](https://datatables.yajrabox.com/eloquent/relationships) that you indeed need to issue a proper select statement to avoid that issue. However, the root cause is still not addressed.

**Comment by cferrante** [comment]
Hello @yajra, when I noticed the hasManyThrough relationship is not yet supported, I tried raw SQL; however, performance is not good enough for the size of data.

I am using "yajra/laravel-datatables-oracle": "^8.4" and would like to help add support for the hasManyThrough relationship type...unless maybe you or someone has done that already?

In EloquentDataTable.joinEagerLoadedColumn, I see where there would need to be a case statement added, but I am not yet expert enough with Laravel 5.6 to accomplish it yet.

Do you have some time to point me in the right direction?

**Comment by cferrante** [comment]
Hello @yajra, 
I am using "yajra/laravel-datatables-oracle": "^8.4" and Laravel 5.6.

I believe I have the code ready for adding support for hasManyThrough relationship. It seems to work; however, I have some questions regarding whether my solution is 100% correct and complete.

Should I make a PR and ask the questions there...or ask them here first?

**Comment by yajra** [comment]
hi @cferrante, please submit a PR so that other users can also review it. Will try to give more time to oss projects this week since 5.7 was already released. I might be able to check this too. Thanks for the help.
