### ISSUE TITLE
[Enhancement] DB::raw with filtering/search

### ISSUE THREAD

**Issue by sameerpanjwani** [yajra/laravel-datatables#43]
I. Whenever I use `DB::raw('CONCAT(field_name_1,field_name_2) AS something')` in the "select", then the search/column filter does't seem to work. I see in the code you're doing something called a wrapColumn which I think is causing it to be escaped and therefore treated as a table column instead of a raw query. 

Can you give some option where we can specify:

`->setColumnSearchType('4','raw') OR setColumnSearchType([4,8],'raw')` //and this will allow you to skip the wrapColumn clause for these columns

It might also be useful to have an additional option:

`->setColumnSearchType('4','raw','having')` //because sometimes when using aggregate functions like "MAX(score) as final_score", if you put them in the "where" condition, they won't work but if you put "HAVING final_score LIKE '%32%'" then it works

II. If pass "column_name as alias", doesn't seem to work but if i put "column_name AS alias", it works, you not allowing lowercase of "as"?

**Comment by yajra** [comment]
can you please paste your js and controller script? will try to replicate the issue. And also, what versions are you using for the package and Laravel? Thanks!

**Comment by yajra** [comment]
Below is an example of how I use an alias and it works for me.

```php
public function getCountData()
    {
        $users = User::select([
            'users.id',
            'users.name',
            'users.email',
            \DB::raw('count(posts.user_id) as count'),
            'users.created_at',
            'users.updated_at'
        ])->join('posts','posts.user_id','=','users.id')
        ->groupBy('posts.user_id');

        return Datatables::of($users)->make(true);
    }
```

```js
$('#users-table').DataTable({
        processing: true,
        serverSide: true,
        ajax: 'http://datatables.app/eloquent/count-data',
        columns: [
            {data: 'id', name: 'users.id'},
            {data: 'name', name: 'users.name'},
            {data: 'email', name: 'users.email'},
            {data: 'count', name: 'count', searchable: false},
            {data: 'created_at', name: 'users.created_at'},
            {data: 'updated_at', name: 'users.updated_at'}
        ]
    });
```

**Comment by sameerpanjwani** [comment]
1. Alias issue minor, ignore

2. In your example itself:

a. I want the "count" field to be searchable, that's why suggested if there was something like (using your example)

->setColumnSearchType('3','raw','having')  //where 3 is the 'count' column

and it will then execute the query like "{your query} HAVING count LIKE '%$search_word%'"

b. sometimes (using your example again), we want to do a CONCAT. 

So if I did:

$users = User::select([
            DB::raw("CONCAT(users.id,'-',users.name) as some_alias"),
            'users.name',
            'users.email',
            \DB::raw('count(posts.user_id) as count'),
            'users.created_at',
            'users.updated_at'
        ])
->setColumnSearchType('0','raw')
join('posts','posts.user_id','=','users.id')
        ->groupBy('posts.user_id');

Ideally when we do a search, it will then do a

WHERE CONCAT(users.id,'-',users.name) LIKE '%abc%'

**Comment by yajra** [comment]
- I got your point on the `count` where clause. Will consider that on the **next release**.
- For the concat part, what I usually do as a work around was set the name attribute on javascript to some field that is searchable like `{data: 'some_alias', name: 'users.name'},`. However, I got the point here that there is a difference in a concat value search than a field search. Will also try to do this on the **next release**

On the other hand, while this enhancements are not yet done. I suggest you use the `filter` function and just write your complex where clause there as a work around.

Btw, I also accepts PR if ever you want to implement the solutions you have in mind. Thanks reporting this.

**Comment by yajra** [comment]
@sameerpanjwani , i just updated the master branch and implemented the `filterColumn` function which on my opinion will accommodate your request. If you have spare time, kindly checkout `dev-master` branch. I still need to do some more testing before releasing it to `v5.1` and it would be a great help if you could find some time to test it. The master branch also has a new feature that extends the Query Builder class directly which means that you can do custom filtering like a normal query in Laravel but using `Datatables` class. Thanks!

Demo controller script. Full working code is available at [DT Demo App](https://github.com/yajra/laravel-datatables-demo)
```php
public function getAdvanceFilterData(Request $request)
{
    $users = User::select([
            \DB::raw("CONCAT(users.id,'-',users.id) as id"),
            'users.name',
            'users.email',
            \DB::raw('count(posts.user_id) AS count'),
            'users.created_at',
            'users.updated_at'
    ])->leftJoin('posts','posts.user_id','=','users.id')
    ->groupBy('users.id');

    $datatables =  Datatables::of($users);
    if ($request->get('post')) {
        // having count search
        $datatables->having('count', $request->get('operator'), $request->get('post'));
    }

    if ($name = $request->get('name')) {
        $datatables->where('users.name', 'like', "$name%"); // additional users.name search
    }

    // Global search function
    if ($keyword = $request->get('search')['value']) {
        // override users.name global search
        $datatables->filterColumn('users.name', 'where', 'like', "$keyword%");

        // override users.id global search - demo for concat
        $datatables->filterColumn('users.id', 'whereRaw', "CONCAT(users.id,'-',users.id) like ? ", ["%$keyword%"]);
    }

    return $datatables->make(true);
}
```

**Comment by sameerpanjwani** [comment]
Ok great will try to test it out over the next 24h and get back to you.

**Comment by sameerpanjwani** [comment]
Issues:

1. filterColumn doesn't work with Query Builder because it seems that your doFiltering() function is calling $query->getQuery() on 1016 but that method doesn't exit in Query Builder. So I think you need to either put this in your EloquentEngine or put an if..else condition

Otherwise for Eloquent seems to be fine

2. Although it would be great if there was some way we didn't have to repeat the condition in filterColumn for all raw queries. Your filterColumn function is really useful for simple and complex queries and a lot of things are possible with this feature. It's quite useful. But for most cases, it would be good (not sure how though or even if possible) if we could: 

$datatable->setColumnSearchType('1','whereRaw'); and it would automatically do a filterColumn picking the query from how it was defined. Not very familiar with Laravel's query builder internals if possible to extract db raw query, but if possible, then this  might be an easier alternative for most user's use cases. 

I like the filterColumn approach though, it's very nice!

3. This is unrelated but you seem to be depending on the column names specified in the JS, which I don't think is very safe. It would be great if you depended on Query Columns directly, even if someone did not pass name in the JS. Maybe have a setColumnName feature as a function to do it from PHP. Just not sure if a good idea to depend on JS for it.

**Comment by yajra** [comment]
**Issue**
Thanks for the feedback. Forgot to test the new feature on Query Builder and have used only Eloquent on my demo/testing app. Anyways, filterColumn for Query Builder should be fixed on v5.1.1.

In connection to filterColumn, the credits goes to the one who PR it on Bllim's version. I just basically get the idea there and enhanced it.

-----
For `setColumnSearchType`, the problem there was parameters will vary depending on Laravel's query builder function and I can't think any workaround/solution on how to implement it properly.

-----
For the names specified in JS, I have decided to put it there for better flexibility. The original design of the package does indeed uses the column selected on query but the problem is that we rely so much in the order of the columns when displaying it. But by using the name in JS, we can basically place the data in any order in the table without the need to adjust the server side select sequence. And I think this approach will work much better especially if you plan to use the advance features of datatables.

For the security part, Laravel automatically wraps the column when creating the query and I think it will make our query builder secure and we also use bindings on our source. However, I am not a security expert so I can't be so sure about the possibility of SQL injection and any other possible attacks.

**Comment by sameerpanjwani** [comment]
Understood. Just is there any option you have built in or already available from the original package to use columns from the query instead of specifying in the JS. I understood your point about the flexibility. Just wondering if there already a way built in that you’ve not documented on whether possible to use columns specified in select instead of js? If not, it’s fine but was wondering if by any chance there was already a way.

**Comment by yajra** [comment]
When you use `make()` without `true` parameter. It will base it's query on the selected columns. However, it will return your data as array and not an object.

**Comment by sameerpanjwani** [comment]
I tried false in your latest version but things don’t work as intended, in your previous version 4.x it used to work.

**Comment by yajra** [comment]
I haven't tried it using a complex query. But for basic/simple queries, it should work as expected. I guess I have to do more demo for `make(false)` to test it well. It's been a habit of mine to always declare the columns on js since I migrated to DT1.10 and have overlooked this one.

**Comment by sameerpanjwani** [comment]
Ok no problem, thanks for everything. I hope the filterColumn fix will come soon for Query Builder because that’s what we use mostly.

 

And great work with all the support you offer and how pro-active you are with the plugin. Amazing! :)

**Comment by yajra** [comment]
I already released v5.1.1. It should be downloadable by now.

**Comment by sameerpanjwani** [comment]
**Found an issue where search doesn't work column wise using the filterColumn.**

Refer the eloquent/multi-filter-select example script.

Change the code as following:

*In the controller:*

```php
 public function getMultiFilterSelectData()
    {
        $users = User::select([  \DB::raw("CONCAT(users.id,'-',users.id) as user_id"), 'name', 'email', 'created_at', 'updated_at']);

        // Global search function
        if ($keyword = \Request::get('search')['value']) {
            // override users.name global search

          // override users.id global search - demo for concat
          $users ->filterColumn('user_id', 'whereRaw', "CONCAT(users.id,'-',users.id) like ?", ["%$keyword%"]);
        }


        return Datatables::of($users)->make(true);
    }
```

*In the blade:*
Replace "id" with "user_id" as follows:
*{data: 'user_id', name: 'user_id'}*

**Issue**

The filter search doesn't work on the concatenated column. Try searching for anything on the column 1 filter.

**Comment by yajra** [comment]
@sameerpanjwani `filterColumn` should be called within the `Datatables` class and not on Query itself.

```php
public function getMultiFilterSelectData()
{
    $users = User::select([  \DB::raw("CONCAT(users.id,'-',users.id) as user_id"), 'name', 'email', 'created_at', 'updated_at']);
    $datatables = Datatables::of($users);

    // Global search function
    if ($keyword = \Request::get('search')['value']) {
        // override users.name global search

      // override users.id global search - demo for concat
      $datatables->filterColumn('user_id', 'whereRaw', "CONCAT(users.id,'-',users.id) like ?", ["%$keyword%"]);
    }


    return $datatables->make(true);
}
```

**Comment by sameerpanjwani** [comment]
Sorry about typo. But still fails, basically the aggregate queries return a
column doesnt exist error.

**Comment by yajra** [comment]
OIC, the issue was on the individual column search. But with the global search, it's working as expected. Thanks for reporting. Will create a new issue for that and closing this one.

**Comment by yajra** [comment]
@sameerpanjwani , filterColumn should now be fixed on v5.1.2. Thanks!
